spring:
  application:
    name: finance-manager
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: false

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:financedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.rubrangso.finance: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:financedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
server:
  servlet:
    session:
      cookie:
        secure: true

logging:
  level:
    root: WARN
    com.rubrangso.finance: INFO
